VC to VC role add & rewrite #108
pistachiostudio/takohachi pull request #109
Opened 2023-01-12 10:56 UTC by quojama

fixed!  
Print is 大事

2023-01-12 14:23 UTC, zztkm requested changes
2 点コメントしたので確認おねがいします！

2023-01-12 14:23 UTC, zztkm commented on src/cogs/vc_role.py
> +            elif after.channel.id == KYORYU_VC_ID:
[must]

ここの条件分岐の最後に else (どれにも該当しなかった場合) がないです。

予期せぬ動作を防ぐためにもどれにも該当しなかった場合の処理を書いておく必要があると思いますので実装おねがいします 🌮

2023-01-12 14:23 UTC, zztkm commented on src/cogs/vc_role.py
> +                await member.add_roles(role_inu, role_mood)
[check]
以降全ての処理にいえますが、ロールを付与したら return しなくても問題ないですか？

2023-01-13 00:24 UTC, quojama commented on src/cogs/vc_role.py
> +            elif after.channel.id == KYORYU_VC_ID:
passを追記してPushしてみました。

2023-01-13 00:25 UTC, quojama commented on src/cogs/vc_role.py
> +                await member.add_roles(role_inu, role_mood)
俺的にはreturnは不要と思っていますがどういう場合にreturnが必要でしょうか。

2023-01-13 00:41 UTC, zztkm approved these changes
LGTM 🦖

2023-01-13 00:42 UTC, merged