[WIP] Purge Messageを追加
pistachiostudio/takohachi pull request #120
Opened 2023-01-27 09:29 UTC by quojama

![image](https://user-images.githubusercontent.com/4445606/215052991-1a7d676f-6ba1-427b-b724-ad5e9717eff2.png)

こんな感じのシンプルなログにしてみました。

一応動作確認完了。Docker起動も確認済 (大事)

一旦wipでレビューでお願いします。一応autodelete.pyは残しとく

2023-01-27 09:59 UTC, zztkm commented on src/cogs/purge.py
> +import logging
auto_delete を変更すればよいのでは？

なんでわけているのか理由があったら説明ほしいです 🦙

2023-01-27 10:08 UTC, quojama commented on src/cogs/purge.py
> +import logging
分けている理由としまして、

1. autodeleteとりpurgeという名前を使いたい
2. もしpurgeに不測の事態があった場合、おれがrevertの手順をよくわからないので最悪extensionの読み込みだけを変えて対応ができるようにしたかった
3. おいおいは全然消していいと思っている

2023-01-27 12:10 UTC, zztkm commented on src/cogs/purge.py
> +import logging
2 教えるのでやり方です覚えてください

2023-01-28 02:57 UTC, zztkm requested changes
コメントつけた内容について対応お願いします :tak

2023-01-28 02:57 UTC, zztkm commented on src/cogs/purge.py
> +import logging
revert は必要になったらやり方を教えます（めちゃくちゃ簡単です）

2023-01-29 00:58 UTC, quojama commented on src/cogs/purge.py
> +import logging
今日試してみる

2023-01-31 11:22 UTC, quojama commented
@zztkm tkm reviewを反映。

ついでに

- .logファイルに日付を埋め込む記述をする必要がないということがわかったので変えた
- discordのbot-testカテゴリ配下に2つチャンネル作ったのでテスト用IDをそれに変えた

もやった

2023-02-01 01:30 UTC, zztkm requested changes
ぱっと見気になったところにコメントをつけました

2023-02-01 04:45 UTC, quojama commented on src/cogs/autodelete.py
> +            deleted = await channel.purge(limit=purge_count, check=is_not_pinned)
調べてみたがピンと来るのがなく、なにか参考になりそうなものある？
beforeはPython? それとも dpy?

2023-02-01 05:19 UTC, zztkm commented on src/cogs/autodelete.py
> +            deleted = await channel.purge(limit=purge_count, check=is_not_pinned)
あー、すみません、purge のヒキスウの話です

2023-02-01 11:04 UTC, quojama commented on src/cogs/autodelete.py
> +            deleted = await channel.purge(limit=purge_count, check=is_not_pinned)
理解。これで良さそうな気が

```python
deleted = await channel.purge(limit=purge_count, check=is_not_pinned, before=message)
logging.info(f'Purged {len(deleted)} messages in {channel.name} (pinned: {pinned_count})')
```

2023-02-01 12:19 UTC, quojama commented on src/cogs/autodelete.py
> +            deleted = await channel.purge(limit=purge_count, check=is_not_pinned)
上は全然ダメ。
add before args の変更がいい感じかな～とおもう。たぶん... ローカルタイムとUTCの検証に時間かかった。

```
渡された日付、またはメッセージより前のメッセージを取得します。
日付を指定する場合、UTC aware datetimeを利用することを推奨します。
naive datetimeである場合、これはローカル時間であるとみなされます。
```

2023-02-01 14:25 UTC, quojama commented on src/cogs/autodelete.py
> +                return not message.pinned and now - message_time > channel_list[channel_id]
確かに。実験してみるかー

2023-02-01 14:32 UTC, quojama commented on src/cogs/autodelete.py
> +                return not message.pinned and now - message_time > channel_list[channel_id]
これでテストしてみます。30分と6時間で見てみます。

![image](https://user-images.githubusercontent.com/4445606/216071132-e80ff2e9-93e3-40db-8735-f12466357bf2.png)

起動時に消えてないということは問題なさそうかも

![image](https://user-images.githubusercontent.com/4445606/216071297-41e9703c-360a-47d5-bb8e-cc1779a69395.png)

2023-02-02 00:43 UTC, quojama commented
なんか問題あったらすぐ対応できないので夜にマージする。一応これでOKかと！

2023-02-02 02:17 UTC, zztkm approved these changes
LGTM 🦖

2023-02-02 02:17 UTC, zztkm commented on src/cogs/autodelete.py
> +                return not message.pinned
ok

2023-02-02 11:14 UTC, merged