add countall command
pistachiostudio/takohachi pull request #39
Opened 2021-12-24 12:55 UTC by quojama

### '!!countall' コマンドの追加

犬～恐竜 4チャンネルのメッセージの合計を返します。コードがダサいのはかんべんかまぼこ。

それに伴う '!!help' コマンドの更新 。

2021-12-27 11:01 UTC, zztkm requested changes
何点かコメントしているので確認して対応お願いします！

2021-12-27 11:01 UTC, zztkm commented on cogs/message_count.py
> +        ttl_count = int(inu_ttl_count) + int(neko_ttl_count) + int(kame_ttl_count) + int(kyoryu_ttl_count)
上の counter を1つにする & 僕が実装するなら以下のようにします。

説明
- couter は共通化
- 文字列フォーマットはトータルを計算し終わったあとにする

```python
        async for _ in inu_id.history(limit=None):
           counter += 1

        async for _ in neko_id.history(limit=None):
            counter += 1

        async for _ in kame_id.history(limit=None):
            counter += 1

        async for _ in kyoryu_id.history(limit=None):
            counter += 1

        ttl_count = f"{counter:,}"
```

2021-12-30 10:21 UTC, quojama commented on cogs/message_count.py
> +        ttl_count = int(inu_ttl_count) + int(neko_ttl_count) + int(kame_ttl_count) + int(kyoryu_ttl_count)
少しだけ理解 & fixed

2021-12-30 10:21 UTC, quojama commented on cogs/commandslist.py
> +        embed.description = "Prefix は `!!` です。\n[View more info on GitHub](https://github.com/pistachiostudio/takohachi/blob/master/mannual.md)\n\n**mt**\n```まりもたいむ！```\n**whatToday**\n```今日はなんの日？```
助かり & fixed

2021-12-30 15:44 UTC, zztkm approved these changes
いい感じです！LGTM 👍🏼

2021-12-30 16:44 UTC, merged