docker review plz
pistachiostudio/takohachi pull request #85
Opened 2022-10-22 11:17 UTC by quojama

@zztkm 

.envファイルにクレデンシャル系全部記述して

`$ docker compose up`

で Yeah bot is on ready! まで来た！

永続化なども必要になってくるのだろうか？多分これではまだ不十分なのかもしれない。

なにか足りないところあったら教えてほしいです。

2022-10-22 12:55 UTC, zztkm commented
OK レビューします
ー
TKM


2022年10月22日(土) 20:17 Yuki Koyama ***@***.***>:

> @quojama <https://github.com/quojama> requested your review on: #85
> <https://github.com/pistachiostudio/takohachi/pull/85> docker review plz.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/pistachiostudio/takohachi/pull/85#event-7645744435>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIBRELRPPAGYMZ6N5KWHZLDWEPEN5ANCNFSM6AAAAAARLZZCQA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2022-10-22 13:11 UTC, zztkm requested changes
全体的にいい感じだと思います。
細かい部分をいくつか書いておきました！

2022-10-22 13:11 UTC, zztkm commented on Dockerfile
> +COPY . /app
個人的にここでは requirements.txt だけを指定してコピーすると良いと思います。
環境構築に他のファイルは不要なので 🤔 

```
COPY requirements.txt  /app
```

2022-10-22 13:11 UTC, zztkm commented on Dockerfile
> +CMD ["python3.10", "launcher.py"]
> CMD ["python3.10", "launcher.py"]

これは docker-compose を使う前提なら不要です。

docker-compose 側でコマンドを定義できます 🦖

2022-10-22 13:11 UTC, zztkm commented on docker-compose.yml
> +      - .env
Dockerfile で CMD とかアプリケーションコードのコピーをしないようにした場合、以下の追加が必要です。

```yaml
    env_file:
      - .env
    volumes:
      - .:/app
    command: python3 launcher.py
```

2022-10-22 13:11 UTC, zztkm commented on docker-compose.yml
> +      - .env
volumes でマウントしておくと docker を停止しても生成されたファイルとかはホストOS上に残ります

2022-10-22 13:22 UTC, quojama commented
ty!

2022-10-22 17:28 UTC, quojama commented
@zztkm 

- [x] dockerをtkm reviewに修正
- [x] requirements.txt を見直し (依存関係OKなはずだけど一応コメントアウトで残し)
- [x] .gitignore少しだけ見直し
- [x] dispanderの使用をやめることにした
- [x] 各.pyファイルのimportを慣習通りソート
  - [x] さらに末尾に改行が一つはいってないものは入れた

以上を対応し、`docker compose up` で問題なく立ち上がることを確認。

これで問題なさそうだったらマージ後Herokuにもpushして、dispanderを本番でもストップ。別のURL展開BOTを入れる。

2022-10-23 09:07 UTC, zztkm approved these changes
OK

2022-10-23 12:37 UTC, merged