一応動いた
pistachiostudio/takohachi pull request #92
Opened 2022-12-23 15:08 UTC by quojama

一定時間経過でメッセージを消していくやつ。一応これで1チャンネル分動いた。エポック時間で計算する。

この1チャンネル分に対して、複数チャンネル分を記述する場合、どのように書くのが負荷をかけず、更にスマートなのかな？

```python
    @tasks.loop(seconds=600.0)
    async def printer(self):
        channel = self.bot.get_channel(int('780611197350576200'))

        now = int(time.time())

        counter = 0
        async for message in channel.history():
            message_time = int(message.created_at.timestamp())
            if now-message_time > 43200:
                await message.delete()
            counter += 1

    @tasks.loop(seconds=600.0)
    async def printer(self):
        channel = self.bot.get_channel(int('別のID'))

        now = int(time.time())

        counter = 0
        async for message in channel.history():
            message_time = int(message.created_at.timestamp())
            if now-message_time > 43200:
                await message.delete()
            counter += 1
```

こんな感じで適用させたいチャンネル分縦に書くくらいしか思いつかないんだけども... 非同期だから一応同時に動くんだよなあ...(?)

2022-12-23 15:24 UTC, quojama commented
デコレータ連発の書き方はだめなのか。一番下に書いたやつしか動いてないな

2022-12-23 16:53 UTC, quojama commented
おれにはこれしか思いつかない！これでもずいぶんスリムになった気がするが。思ったよりめちゃくちゃ短くかけた。

2022-12-24 08:07 UTC, zztkm requested changes
コメントしました！
参考にしてください 🔢

2022-12-24 08:07 UTC, zztkm commented on cogs/autodelete.py
> +                        print(f"  🗑deleted message in {channel.name}")
[imo]

おれならこうします

```python
async for message in channel.history(oldest_first=True):
    # メッセージがピン留めされていたらスキップ
    if message.pinned:
        continue # 処理をスキップ

    # メッセージの投稿時間をUNIX時間に変換
    message_time = int(message.created_at.timestamp())

    # 現在時間からメッセージの投稿時間を引いて、指定した時間よりも古いかどうかを確認
    if now - message_time > channel_list[channel_id]:
        await message.delete()
        print(f"  🗑deleted message in {channel.name}")
```

2022-12-24 08:07 UTC, zztkm commented on cogs/autodelete.py
> +                        print(f"  🗑deleted message in {channel.name}")
極力 if 条件が入れ子にならないようにした方が見通しが良いです。

あと判定用の変数を作っても 1 回しか参照しないし、変数化しなくても特に支障ないならわざわざ変数にしない方がわかりやすいと思います

2022-12-24 17:12 UTC, quojama commented
@zztkm Thank you! レビューを修正した。printログは削除して、一旦これでマージして本場環境にデプロイして負荷を見てみる。
  
現状10分ごとにループ回します。負荷が高い場合はlauncherから切り離して止めてローカルでたまに動かすなど？を考えようと思います。

2022-12-24 17:35 UTC, merged